export { default as About } from './About';
export { default as Blog } from './Blog';
export { default as Blogs } from './Blogs';
export { default as Blogpost } from './Blogpost';
export { default as BlogPostDetails } from './Blogpostdetails';
export { default as Chat } from './Chat';
export { default as DetailedSubmission } from './DetailedSubmission';
export { default as Dashboard } from './Dashboard';
export { default as Exam } from './Exam';
export { default as Home } from './Home';
export { default as Faq } from './Faq';
export { default as Learn } from './Learn';
export { default as Login } from './Login';
export { default as Notification } from './Notification';
export { default as PageNotFound } from './PageNotFound';
export { default as Posts } from './Posts';
export { default as Profile } from './Profile';
export { default as Pricing } from './Pricing';
export { default as Quiz } from './Quiz';
export { default as Quize } from './Quize';
export { default as Quizzes } from './Quizzes';
export { default as Reset } from './Reset';
export { default as Result } from './Result';
export { default as Resulto} from './Resulto';
export { default as Service } from './Service';

export { default as SignUp } from './SignUp';
export { default as Submissions } from './Submissions';

export { default as Video } from './Video';
